package entities;
// Generated Oct 31, 2022, 8:22:32 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cart generated by hbm2java
 */
@Entity
@Table(name = "cart", catalog = "miniShop")
public class Cart implements java.io.Serializable {

	private CartId id;
	private int quantity;
	private Long userId;
	private Date addedDate;

	public Cart() {
	}

	public Cart(CartId id, int quantity, Date addedDate) {
		this.id = id;
		this.quantity = quantity;
		this.addedDate = addedDate;
	}

	public Cart(CartId id, int quantity, Long userId, Date addedDate) {
		this.id = id;
		this.quantity = quantity;
		this.userId = userId;
		this.addedDate = addedDate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "cartId", column = @Column(name = "CartId", nullable = false, length = 32)),
			@AttributeOverride(name = "productId", column = @Column(name = "ProductId", nullable = false)) })
	public CartId getId() {
		return this.id;
	}

	public void setId(CartId id) {
		this.id = id;
	}

	@Column(name = "Quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "userId")
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AddedDate", nullable = false, length = 19)
	public Date getAddedDate() {
		return this.addedDate;
	}

	public void setAddedDate(Date addedDate) {
		this.addedDate = addedDate;
	}

}
