package entities;
// Generated Oct 31, 2022, 8:22:32 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Userinrole generated by hbm2java
 */
@Entity
@Table(name = "userinrole", catalog = "miniShop")
public class Userinrole implements java.io.Serializable {

	private UserinroleId id;

	public Userinrole() {
	}

	public Userinrole(UserinroleId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "roleId", column = @Column(name = "RoleId", nullable = false)),
			@AttributeOverride(name = "userId", column = @Column(name = "userId", nullable = false)) })
	public UserinroleId getId() {
		return this.id;
	}

	public void setId(UserinroleId id) {
		this.id = id;
	}

}
